name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.txt'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    name: test (ruby:${{ matrix.ruby }}, ar:${{ matrix.ar }})

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: 'activerecord_unittest'
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10
 
    strategy:
      fail-fast: false
      matrix:
        ruby: ['3.1', '3.2', '3.3']
        ar: ['7.0', '7.1', '7.2', '8.0']
        exclude:
          - ruby: '3.1'
            ar: '8.0'

    env:
      BUNDLE_GEMFILE: gemfiles/ar_${{ matrix.ar }}.gemfile

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
